name: Go
on: [push]
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        mkdir -p /home/runner/go/bin
        export PATH="$PATH:/home/runner/go/bin"
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Define version as branch
      run: |
        VERSION=${GITHUB_REF##*/}
        echo $VERSION > version.info

    - name: Define version if it master
      if: ${{ github.ref == 'refs/heads/master'}}
      run: |
        VERSION=`git describe --tags --long`
        echo $VERSION > version.info

    - name: Define version if it on tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=`git describe --tags --long`
        echo $VERSION > version.info

    - name: Build
      run: |
        VERSION=`cat version.info`
        CGO_ENABLED=0 go build -a -v -ldflags "-X main.version=$VERSION -extldflags '-static'" .
    - name: Test
      run: go test .

  build-windows:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.13.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -a -v .
